---
title: "tables-by-type-child"
output: html_document
---
```{r, include=FALSE}

wrk_tbl <- NULL
numeric_columns <- c('2017 Pop','2050 Pop','Pop Growth','2017 Job','2050 Job','Job Growth')
percent_columns <- c('Pop Percent','Job Percent')

wrk_tbl <- data.table(Area=wrk_nms,`2017 Pop`=unlist(results_by_type[[r1]]),`2050 Pop`=unlist(results_by_type[[r2]]),`Pop Growth`=unlist(results_by_type[[r3]]),`Pop Percent`=unlist(results_by_type[[r4]]),`2017 Job`=unlist(results_by_type[[r5]]),`2050 Job`=unlist(results_by_type[[r6]]),`Job Growth`=unlist(results_by_type[[r7]]),`Job Percent`=unlist(results_by_type[[r8]]))

wrk_tbl$Area <- factor(wrk_tbl$Area, levels = wrk_ord)
wrk_tbl <- wrk_tbl[order(Area),]

pop_job_table_container <- create_table_container('Area Type', summary_attributes, summary_columns)
clean_tbl <- datatable(wrk_tbl, container = pop_job_table_container, rownames = FALSE, options = list(pageLength = 15, columnDefs = list(list(className = 'dt-center', targets =1:8))))

for (working_column in numeric_columns) {
  clean_tbl <- clean_tbl %>% 
    formatCurrency(working_column, "", digits = 0) %>%
    formatStyle(working_column,`text-align` = 'center')
}

for (working_column in percent_columns) {
    clean_tbl <- clean_tbl %>% 
      formatPercentage(working_column,0) %>%
      formatStyle(working_column,`text-align` = 'center')
}

```

## `r header_names`

```{r, echo=FALSE, results="asis"}
clean_tbl
```